









































}    }                    ]);                        'otp' => $this->otp,                        'name' => $this->name,                    ->with([                    ->view('emails.otp')        return $this->subject('Kode OTP Anda')    {    public function build()     */     * @return $this     *     * Build the message.    /**    }        $this->otp = $otp;        $this->name = $name;    {    public function __construct(string $name, string $otp)     */     * @param string $otp     * @param string $name     *     * Create a new message instance.    /**    public $otp;    public $name;    use Queueable, SerializesModels;{class OtpMail extends Mailableuse Illuminate\Queue\SerializesModels;use Illuminate\Mail\Mailable;use Illuminate\Bus\Queueable;namespace App\Mail;<?php